export const VI_TRI_DAT_VE = "VI_TRI_DAT_VE"
export const PHAN_TRANG_TIM_KIEM ="PHAN_TRANG_TIM_KIEM"
export const POST_VI_TRI ="POST_VI_TRI"
export const DS_VI_TRI_ID ="DS_VI_TRI_ID"
export const PUT_VI_TRI_ID ="PUT_VI_TRI_ID"
export const DELETE_VI_TRI_ID ="DELETE_VI_TRI_ID"